name: wechat_simulator
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_native_splash: 2.1.6
  shared_preferences: 2.0.15
  provider: 6.0.3
  logging:
  #extended_image: ^6.2.1
  lpinyin: ^2.0.3
  event_bus: ^2.0.0
  http: ^0.13.4
  shirne_dialog: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  flutter_launcher_icons_maker: 0.10.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: appIconFont
      fonts:
       - asset: assets/fonts/iconfont.ttf

# flutter pub run flutter_launcher_icons_maker:main
flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  macos: true
  windows: true
  web: true
